create database customer_behaviour;
select * from customer; 
-- Total revenue generated by male vs. female customers
select gender,sum(purchase_amount) as revenue 
from customer
group by 1;



-- Customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount,discount_applied
from customer
where discount_applied='Yes'
and purchase_amount>(select avg(purchase_amount) from customer) ;

-- Top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2)  
from customer
group by 1
order by avg(review_rating) desc limit 5
;

-- Average Purchase Amounts between Standard and Express Shipping.
select round(avg(purchase_amount),2), shipping_type
from customer
where shipping_type='Express' or shipping_type='Standard'
group by 2;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select distinct subscription_status, count( distinct customer_id),avg(purchase_amount),sum(purchase_amount)
from customer
group by 1;


-- Top 5 products with the highest percentage of purchases with discounts applied
select item_purchased,round(100.0 * sum(case when discount_applied='Yes' then 1 else 0 end )/count(*),2)
from customer
group by 1
order by 2 desc limit 5;


--  New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as (select customer_id,(case
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end
) as customer_segment
from customer)

select customer_segment, count(customer_id)
from customer_type
group by 1;




-- Top 3 most purchased products within each category
select item_purchased ,category, total_count from
(select item_purchased ,category,count(*) as total_count ,
dense_rank() over (partition by category order by count(*) desc) as rnk from customer group by 1,2) t
where rnk<=3
;


-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by 1;

-- Revenue contribution of each age group
select age_group, sum(purchase_amount) 
from customer 
group by age_group
order by 2 desc;